---
title: "Дашбоард по Lichess"
editor: visual
---

```{r}
library(ggplot2)
library(data.table)
theme_set(theme_bw())
```

```{r}
df <- fread(Sys.getenv("PATH_DATAS"))
rt_p1 <- df[name==Sys.getenv("PLAYER_ONE") & !is.na(rp_game), last(rp_game)]
rt_p2 <- df[name==Sys.getenv("PLAYER_TWO") & !is.na(rp_game), last(rp_game)]
dev_rt1 <-  df[name==Sys.getenv("PLAYER_ONE") & !is.na(deviation), last(deviation)]
dev_rt2 <-  df[name==Sys.getenv("PLAYER_TWO") & !is.na(deviation), last(deviation)]
rp_puz1 <- df[name==Sys.getenv("PLAYER_ONE") & !is.na(rp_puzzles), last(rp_puzzles)]
rp_puz2 <- df[name==Sys.getenv("PLAYER_TWO") & !is.na(rp_puzzles), last(rp_puzzles)]

sum_puz1 <- df[name==Sys.getenv("PLAYER_ONE") & !is.na(win_puzzles),
               sum((win_puzzles+loss_puzzles+draw_puzzles))]
sum_puz2 <- df[name==Sys.getenv("PLAYER_TWO") & !is.na(win_puzzles),
               sum((win_puzzles+loss_puzzles+draw_puzzles))]
```

# Player One

## Row

```{r}
#| content: valuebox
#| title: "Рейтинг"


list(
  color = "primary",
  value = rt_p1
)

```

```{r}
#| title: "Отклонение рейтинга"
#| content: valuebox
list(
  color = "primary",
  value = dev_rt1
)      
  
```

```{r}
#| content: valuebox
#| title: "Рейтинг решения задач"
list(
  
  color = "primary",
  value = rp_puz1)

```

```{r}
#| content: valuebox
#| title: "Решено задач"
list(
  
  color = "primary",
  value = sum_puz1)
```

## Row

### Column {.tabset}

```{r}
#| title: "Рейтинг"
#df1 %>% select(rp_game, dtm) %>% drop_na() %>% ggplot(aes(dtm, rp_game)) + geom_line() +
#  labs(title = "", x="", y="")
df[name==Sys.getenv("PLAYER_ONE") & !is.na(rp_game), .(rp_game, dtm)] |>  ggplot(aes(dtm, rp_game)) + geom_line() +
  labs(title = "", x="", y="")
```

```{r}
#| title: "Выигранные, проигранные партии и ничьи"
df[name==Sys.getenv("PLAYER_ONE") & !is.na(win_game),
   .(dtm, win_game, loss_game, draw_game)] |>
   melt(id.vars = "dtm",
        measure.vars = patterns("game") ,
        variable.name = "name",
        value.name = "count") |> 
   ggplot(aes(dtm, count, fill = name)) +
   geom_bar(stat = "identity") +
   theme(legend.position = "none") +
   labs(title = "", x="", y="")
```

### Column {.tabset}

```{r}
#| title: "Рейтинг решения задач"
df[name==Sys.getenv("PLAYER_ONE") & !is.na(rp_puzzles),
   .(rp_puzzles, dtm)] |>
   ggplot(aes(dtm, rp_puzzles)) +
   geom_line() +
  labs(title = "", x="", y="")
```

```{r}
#| title: "Решенные и не решенные задачи"
df[name==Sys.getenv("PLAYER_ONE") & !is.na(win_puzzles),
   .(dtm, win_puzzles, loss_puzzles, draw_puzzles)] |>
   melt(id.vars = "dtm",
        measure.vars = patterns("puzzles") ,
        variable.name = "name",
        value.name = "count") |> 
   ggplot(aes(dtm, count, fill = name)) +
   geom_bar(stat = "identity") +
   theme(legend.position = "none") +
   labs(title = "", x="", y="")
```

# Player Two

## Row

```{r}
#| content: valuebox
#| title: "Рейтинг"


list(
  color = "primary",
  value = rt_p2
)

```

```{r}
#| title: "Отклонение рейтинга"
#| content: valuebox
list(
  color = "primary",
  value = dev_rt2
)      
  
```

```{r}
#| content: valuebox
#| title: "Рейтинг решения задач"
list(
  
  color = "primary",
  value = rp_puz2)

```

```{r}
#| content: valuebox
#| title: "Решено задач"
list(
  
  color = "primary",
  value = sum_puz2
)
```

## Row

### Column {.tabset}

```{r}
#| title: "Рейтинг"
df[name==Sys.getenv("PLAYER_TWO") & !is.na(rp_game), .(rp_game, dtm)] |>  ggplot(aes(dtm, rp_game)) + geom_line() +
  labs(title = "", x="", y="")
```

```{r}
#| title: "Выигранные, проигранные партии и ничьи"
df[name==Sys.getenv("PLAYER_TWO") & !is.na(win_game),
   .(dtm, win_game, loss_game, draw_game)] |>
   melt(id.vars = "dtm",
        measure.vars = patterns("game") ,
        variable.name = "name",
        value.name = "count") |> 
   ggplot(aes(dtm, count, fill = name)) +
   geom_bar(stat = "identity") +
   theme(legend.position = "none") +
   labs(title = "", x="", y="")
```

### Column {.tabset}

```{r}
#| title: "Рейтинг решения задач"
df[name==Sys.getenv("PLAYER_TWO") & !is.na(rp_puzzles),
   .(rp_puzzles, dtm)] |>
   ggplot(aes(dtm, rp_puzzles)) +
   geom_line() +
  labs(title = "", x="", y="")
```

```{r}
#| title: "Решенные и не решенные задачи"
df[name==Sys.getenv("PLAYER_TWO") & !is.na(win_puzzles),
   .(dtm, win_puzzles, loss_puzzles, draw_puzzles)] |>
   melt(id.vars = "dtm",
        measure.vars = patterns("puzzles") ,
        variable.name = "name",
        value.name = "count") |> 
   ggplot(aes(dtm, count, fill = name)) +
   geom_bar(stat = "identity") +
   theme(legend.position = "none") +
   labs(title = "", x="", y="")
```
