on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      PLAYER_ONE: ${{ secrets.PLAYER_ONE}}
      PLAYER_TWO: ${{ secrets.PLAYER_TWO}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Get dataset
        run: wget "$PATH_DATASET"
        env: 
          PATH_DATASET: ${{ secrets.PATH_DATASET_CSV }}
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R 4.4
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
             
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::dplyr
            any::tidyr
            any::readr
            any::ggplot2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          path: dashboard.qmd
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
