on:
  workflow_dispatch:
  schedule:
    - cron: '45 1 * * *'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R 4.4
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
             
      - name: Install R renv
        uses: r-lib/actions/setup-renv@v2
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        env: 
          PATH_DATASET_CSV: ${{ secrets.PATH_DATASET_CSV }}
          PLAYER_ONE:       ${{ secrets.PLAYER_ONE}}
          PLAYER_TWO:       ${{ secrets.PLAYER_TWO}}
        with:
          target: quarto-pub
          path: dashboard.qmd
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
